package com.pengu.divination;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.pengu.divination.core.iModule;
import com.pengu.divination.proxy.Common;
import com.pengu.divination.totemic.TotemicModule;
import com.pengu.hammercore.HammerCore;
import com.pengu.musiclayer.api.MusicLayer;

import net.minecraft.item.crafting.IRecipe;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLFingerprintViolationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.registries.IForgeRegistry;

@Mod(modid = InfoDC.MOD_ID, version = InfoDC.MOD_VERSION, name = InfoDC.MOD_NAME, dependencies = "required-after:hammercore;required-after:musiclayer", certificateFingerprint = "4d7b29cd19124e986da685107d16ce4b49bc0a97")
public class Divination
{
	public static final List<iModule> modules = new ArrayList<>();
	
	@SidedProxy(serverSide = "com.pengu.divination.proxy.Common", clientSide = "com.pengu.divination.proxy.Client")
	public static Common proxy;
	
	public static TotemicModule totemic = new TotemicModule();
	
	public static final Logger LOG = LogManager.getLogger(InfoDC.MOD_NAME);
	
	@Instance
	public static Divination instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		LOG.info("Performing preInit!");
		MinecraftForge.EVENT_BUS.register(this);
		MinecraftForge.EVENT_BUS.register(proxy);
		meta(e.getModMetadata());
		proxy.preInit();
		
		modules.add(totemic);
		
		for(iModule mod : getModules())
			mod.preInit();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent e)
	{
		LOG.info("Performing init!");
		proxy.init();
		
		for(iModule mod : getModules())
		{
			mod.init();
			mod.getRecipes().smelting();
		}
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent e)
	{
		LOG.info("Performing postInit!");
		for(iModule mod : getModules())
			mod.postInit();
	}
	
	@SubscribeEvent
	public void addRecipes(RegistryEvent.Register<IRecipe> reg)
	{
		IForgeRegistry<IRecipe> fr = reg.getRegistry();
		for(iModule mod : getModules())
			mod.getRecipes().collect() //
			        .stream() //
			        .filter(r -> r != null) //
			        .forEach(fr::register);
	}
	
	public static Collection<iModule> getModules()
	{
		return modules;
	}
	
	@EventHandler
	public void certificateViolation(FMLFingerprintViolationEvent e)
	{
		MusicLayer.LOG.warn("*****************************");
		MusicLayer.LOG.warn("WARNING: Somebody has been tampering with Divination Core jar!");
		MusicLayer.LOG.warn("It is highly recommended that you redownload mod from https://minecraft.curseforge.com/projects/289086 !");
		MusicLayer.LOG.warn("*****************************");
	}
	
	private static ModMetadata meta(ModMetadata md)
	{
		md.authorList = HammerCore.getHCAuthorsArray();
		md.name = InfoDC.MOD_NAME;
		md.modId = InfoDC.MOD_ID;
		md.autogenerated = false;
		md.description = "A mod about several aspects of magic working together.";
		md.version = InfoDC.MOD_VERSION;
		md.logoFile = "logo.png";
		return md;
	}
}