package com.pengu.divination;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.pengu.divination.proxy.Common;
import com.pengu.divination.totemic.TotemicModule;
import com.pengu.hammercore.HammerCore;
import com.pengu.musiclayer.api.MusicLayer;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLFingerprintViolationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = InfoDC.MOD_ID, version = InfoDC.MOD_VERSION, name = InfoDC.MOD_NAME, dependencies = "required-after:hammercore;required-after:musiclayer", certificateFingerprint = "4d7b29cd19124e986da685107d16ce4b49bc0a97")
public class Divination
{
	@SidedProxy(serverSide = "com.pengu.divination.proxy.Common", clientSide = "com.pengu.divination.proxy.Client")
	public static Common proxy;
	
	public static TotemicModule totemic = new TotemicModule();
	
	public static final Logger LOG = LogManager.getLogger(InfoDC.MOD_NAME);
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		LOG.info("Performing preInit!");
		meta(e.getModMetadata());
		proxy.preInit();
		if(totemic != null)
			totemic.preInit();
	}
	
	@EventHandler
	public void certificateViolation(FMLFingerprintViolationEvent e)
	{
		MusicLayer.LOG.warn("*****************************");
		MusicLayer.LOG.warn("WARNING: Somebody has been tampering with Divination Core jar!");
		MusicLayer.LOG.warn("It is highly recommended that you redownload mod from https://minecraft.curseforge.com/projects/289086 !");
		MusicLayer.LOG.warn("*****************************");
	}
	
	private static ModMetadata meta(ModMetadata md)
	{
		md.authorList = HammerCore.getHCAuthorsArray();
		md.name = InfoDC.MOD_NAME;
		md.modId = InfoDC.MOD_ID;
		md.autogenerated = false;
		md.description = "A mod about several aspects of magic working together.";
		md.version = InfoDC.MOD_VERSION;
		md.logoFile = "logo.png";
		return md;
	}
}